name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint > eslint-report.txt

      - name: Run Stylelint
        run: npm run lint:css > stylelint-report.txt 

      - name: Summarize ESLint issues in job summary
        if: always()
        run: |
            echo '## :mag: ESLint Report' >> $GITHUB_STEP_SUMMARY
            echo '<details><summary>Show ESLint Output (first 100 lines)</summary>' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '\n```' >> $GITHUB_STEP_SUMMARY
            head -n 100 eslint-report.txt >> $GITHUB_STEP_SUMMARY
            echo '```\n' >> $GITHUB_STEP_SUMMARY
            echo '</details>' >> $GITHUB_STEP_SUMMARY

      - name: Summarize Stylelint issues in job summary
        if: always()
        run: |
            echo '## :nail_care: Stylelint Report' >> $GITHUB_STEP_SUMMARY
            echo '<details><summary>Show Stylelint Output (first 100 lines)</summary>' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '\n```' >> $GITHUB_STEP_SUMMARY
            head -n 100 stylelint-report.txt >> $GITHUB_STEP_SUMMARY
            echo '```\n' >> $GITHUB_STEP_SUMMARY
            echo '</details>' >> $GITHUB_STEP_SUMMARY

 